### PR TITLE
Add Boxplot in Visual Editor

### PR DESCRIPTION
**Pull request by vitPinchuk**
Resolves: #321

### CODE REVIEW

**Review by asimonok — APPROVED** [review]
Looks good!

@mikhail-vl ready for review

**Review by mikhail-vl — CHANGES_REQUESTED** [review]
@vitPinchuk Please provision botplot dashboard with example

**Comment by vitPinchuk** [comment]
@mikhail-vl provision updated

We should definitely add a point to the documentation that when working with boxplot it is especially important to set the x,y axis correctly

image

**Review by mikhail-vl — APPROVED** [review]
Looks good!

**Pull request merged**
