### PR TITLE
Update refresh for dashboard scene

### PR DESCRIPTION
**Pull request by vitPinchuk**

### CODE REVIEW

**Review by asimonok — CHANGES_REQUESTED** [review]
In tests we should check if useDashboardRefresh is called instead of checking implementation of the hook. Please update tests

**Comment by mikhail-vl** [comment]
@vitPinchuk  Please fix tests after upgrading to Grafana 11.3.0:

```
    console.error
      Warning: Cannot update a component (`Unknown`) while rendering a different component (`mockConstructor`). To locate the bad setState() call inside `mockConstructor`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
          at mockConstructor
          at value (/Users/mikhailvolkov/GitHub/business-charts/node_modules/@volkovlabs/components/src/components/AutosizeCodeEditor/AutosizeCodeEditor.tsx:48:3)
          at div
          at value (/Users/mikhailvolkov/GitHub/business-charts/src/components/EchartsEditor/EchartsEditor.tsx:26:50)

       98 |
       99 |     jest.mocked(CodeEditor).mockImplementationOnce(({ onEditorDidMount }: any) => {
    > 100 |       onEditorDidMount(editor);
          |       ^
      101 |       return null;
      102 |     });
      103 |
```

```
Console

    console.error
      Warning: An update to EchartsPanel inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at options (/Users/mikhailvolkov/GitHub/business-charts/src/components/EchartsPanel/EchartsPanel.tsx:31:49)

      293 |         );
      294 |       } catch (err) {
    > 295 |         setError(err instanceof Error ? err : new Error(`${err}`));
          |         ^
      296 |       }
      297 |     };
      298 |
```

**Review by asimonok — CHANGES_REQUESTED** [review]
Please fix act warnings

**Comment by vitPinchuk** [comment]
> ter upgrading to Grafana 11.3.0:

done

**Review by mikhail-vl — APPROVED** [review]
Looks good!

**Comment by mikhail-vl** [comment]
@asimonok Could you please check and approve?

**Review by asimonok — APPROVED** [review]
Looks good!

**Pull request merged**
